project_name: sniffer
release:
  github:
    owner: sunny0826
    name: kubectl-pod-lens
builds:
  - id: pod-lens
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/sunny0826/kubectl-pod-lens/pkg/version.version=
archives:
  - id: sniffer
    builds:
    - sniffer
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
