apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: pod-lens
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-sniffer/releases/download/v0.0.2/sniffer_linux_amd64.tar.gz
    sha256: "6e6767de74614b7126a6542adbfa3a956ef83d55cb0d0b3d5ac2e7c749669dc5"
    files:
    - from: "./pod-lens"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod-lens"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-sniffer/releases/download/v0.0.2/sniffer_darwin_amd64.tar.gz
    sha256: "d9370b74a5a195e1e16ad71125351bbf55d45f04657f0ecaacf163ca432b84ee"
    files:
    - from: "./pod-lens"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod-lens"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-sniffer/releases/download/v0.0.2/sniffer_windows_amd64.zip
    sha256: "fa97cf65ee8c698648fa43a5f68c2af712ca0eb9d5a75db6f946a4d428fa0291"
    files:
    - from: "/pod-lens.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "pod-lens.exe"
  shortDescription: Sniffing pod-related resources
  homepage: https://github.com/sunny0826/kubectl-pod-lens
  description: |
    Find related workloads, namespace, node, service, configmap, secret,
    ingress and HPA by pod name and display them in a tree and table.
