apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: sniffer
spec:
  version: "v0.0.2"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-sniffer/releases/download/v0.0.2/sniffer_linux_amd64.tar.gz
    sha256: "8ad2f2584c61ed60cc99343d3c56c15592dc7359ce393a7849aa15ca694c9064"
    files:
    - from: "./sniffer"
      to: "."
    - from: LICENSE
      to: "."
    bin: "sniffer"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-sniffer/releases/download/v0.0.2/sniffer_darwin_amd64.tar.gz
    sha256: "310668198d049afdbfc953b66666c3fa266c0f574bad758fc478c5fc00d273f0"
    files:
    - from: "./sniffer"
      to: "."
    - from: LICENSE
      to: "."
    bin: "sniffer"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-sniffer/releases/download/v0.0.2/sniffer_windows_amd64.zip
    sha256: "dc40b7da88807828550f9f54a463d49bb25c19adf84ef47dfba248e33ccfa15c"
    files:
    - from: "/sniffer.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "sniffer.exe"
  shortDescription: Sniffing pod-related resources
  homepage: https://github.com/sunny0826/kubectl-sniffer
  description: |
    Find related workloads, namespace, node, service, configmap, secret,
    ingress and HPA by pod name and display them in a tree and table.
