name: docs
on:
  push:
    paths:
      - 'doc/**'
jobs:
  gh-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to GitHub Repo
        uses: sunny0826/auto-docs-action@v0.0.2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GH_PAGES_DEPLOY }}
          DEPLOYMENT_BRANCH: gh-pages
        with:
          gh-page: git@github.com:sunny0826/pod-lens.github.io.git

