name: docs
on:
  push:
    paths:
      - 'doc/**'
jobs:
  gh-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: 'sunny0826/pod-lens.github.io'
          platform: 'github'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Push to GitHub Repo
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          pwd
          ls
