name: docs
on:
  push:
    paths:
      - 'doc/**'
jobs:
  gh-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Push to GitHub Repo
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git clone --single-branch --depth 1 https://github.com/sunny0826/pod-lens.github.io.git
          pwd
          ls
